name: Google Indexing

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Bu satır robotun yetki hatasını (128) çözer

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # Hata veren submodule kısmını görmezden gelmesini sağlar
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install googleapis axios
        
      - name: Run Indexing Script
        run: node indexing.cjs
        env:
          GOOGLE_INDEXING_KEY: ${{ secrets.GOOGLE_INDEXING_KEY }}