name: Google Indexing

on:
  push:
    branches: [ main ] # Sadece ana şubeye güncelleme gelince çalışır

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Git 128 hatasını kökten çözer
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # En güncel ve uyarı vermeyen versiyon
          
      - name: Install dependencies
        run: npm install googleapis axios
        
      - name: Run Indexing Script
        run: node indexing.cjs
        env:
          GOOGLE_INDEXING_KEY: ${{ secrets.GOOGLE_INDEXING_KEY }}